// site/corpus_compass.ts -- generated by tools/gen-corpus.sh; do not edit.
// The source SVG is the W3C/CVG corpus file compass.svg (cosyne/test/svg).
ui.text("corpus: compass");
ui.hstack(0, () => {
ui.spacer();
const { scene, g, rect, rrect, circle, ellipse, line, path, polygon, polyline, text, text_sized, text_anchored,
        fill, stroke, opacity, transform, linecap, linejoin, defs, linear_gradient, radial_gradient, clip_path } = vg;

scene("0 0 100 100", 400, 400, () => {
  path("M 25 7 L 53 43 L 93 25 L 57 50 L 76 94 L 49 57 L 8 74 L 44 48 Z", () => { fill("#cfc") });
  ellipse(50, 50, 32, 30, () => { fill("none"); stroke("#fc0", 11) });
  path("M 63 2 L 56 45 L 98 62 L 53 56 L 37 98 L 44 53 L 2 37 L 47 43 Z", () => { fill("#3cc") });
});
ui.spacer();
});
ui.btn("Home", () => browserContext.changePage("/"));
