// site/corpus_beacon.ts -- generated by tools/gen-corpus.sh; do not edit.
// The source SVG is the W3C/CVG corpus file beacon.svg (cosyne/test/svg).
ui.text("corpus: beacon");
ui.hstack(0, () => {
ui.spacer();
const { scene, g, rect, rrect, circle, ellipse, line, path, polygon, polyline, text, text_sized, text_anchored,
        fill, stroke, opacity, transform, linecap, linejoin, defs, linear_gradient, radial_gradient, clip_path } = vg;

scene("0 0 100 100", 400, 400, () => {
  g(() => { fill("#F00"); stroke("#3b5998", 4)
    path("M 28 6 L 72 6 L 72 22 L 50 43 L 28 22 Z", () => { fill("#6d84b4") });
    path("M 28 95 L 72 95 L 72 79 L 50 58 L 28 79 Z", () => { fill("#6d84b4") });
    path("M 6 30 L 6 72 L 21 72 L 42 51 L 21 30 Z", () => { fill("#afbfde") });
    path("M 95 30 L 95 72 L 80 72 L 59 51 L 80 30 Z", () => { fill("#afbfde") });
  });
});
ui.spacer();
});
ui.btn("Home", () => browserContext.changePage("/"));
