// site/corpus_atom.ts -- generated by tools/gen-corpus.sh; do not edit.
// The source SVG is the W3C/CVG corpus file atom.svg (cosyne/test/svg).
ui.text("corpus: atom");
ui.hstack(0, () => {
ui.spacer();
const { scene, g, rect, rrect, circle, ellipse, line, path, polygon, polyline, text, text_sized, text_anchored,
        fill, stroke, opacity, transform, linecap, linejoin, defs, linear_gradient, radial_gradient, clip_path } = vg;

scene("-52 -53 100 100", 400, 400, () => {
  g(() => { fill("none")
    ellipse(0, 0, 6, 44, () => { stroke("#66899a", 2) });
    ellipse(0, 0, 6, 44, () => { transform("rotate(-66)"); stroke("#e1d85d", 2) });
    ellipse(0, 0, 6, 44, () => { transform("rotate(66)"); stroke("#80a3cf", 2) });
    circle(0, 0, 44, () => { stroke("#4b541f", 2) });
  });
  g(() => { fill("#66899a"); stroke("white", 2)
    circle(0, 0, 13, () => { fill("#80a3cf") });
    circle(0, -44, 9);
    circle(-40, 18, 9);
    circle(40, 18, 9);
  });
});
ui.spacer();
});
ui.btn("Home", () => browserContext.changePage("/"));
