// site/corpus_heart.ts -- generated by tools/gen-corpus.sh; do not edit.
// The source SVG is the W3C/CVG corpus file heart.svg (cosyne/test/svg).
ui.text("corpus: heart");
ui.hstack(0, () => {
ui.spacer();
const { scene, g, rect, rrect, circle, ellipse, line, path, polygon, polyline, text, text_sized, text_anchored,
        fill, stroke, opacity, transform, linecap, linejoin, defs, linear_gradient, radial_gradient, clip_path } = vg;

scene("0 0 100 100", 400, 400, () => {
  path("M 50 30 C 59 8 92 6 98 30 C 103 70 58 70 50 95 C 42 70 -4 70 2 30 C 8 6 41 8 50 30 Z", () => { fill("#F00"); stroke("#000", 1) });
});
ui.spacer();
});
ui.btn("Home", () => browserContext.changePage("/"));
