#!/bin/sh
# tools/embed-prelude.sh -- regenerate src/sae_prelude.c from src/sae_prelude.js.
# The prelude is JavaScript the host evaluates into every page's runtime
# (src/sae_host.ae, ae_register_); it is embedded as a C string so a packaged
# sae needs no file beside its binary. tests/check_prelude.sh fails when the
# two drift. Run this after editing the .js.
set -e
ROOT=$(cd "$(dirname "$0")/.." && pwd)
JS="$ROOT/src/sae_prelude.js"
OUT="${1:-$ROOT/src/sae_prelude.c}"
{
    echo "/* Generated by tools/embed-prelude.sh from src/sae_prelude.js; do not edit. */"
    echo "const char *sae_prelude(void) {"
    echo "    return"
    sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' -e 's/^/        "/' -e 's/$/\\n"/' "$JS"
    echo "    ;"
    echo "}"
} > "$OUT"
