#!/bin/sh
# tools/gen-corpus.sh -- the parity pages: a few files of the W3C/CVG corpus
# (ideas from Tsyne's cosyne/test/svg; the files carry their own licences,
# the small W3C shapes state none, AJ_Digital_Camera says public domain)
# emitted as AeVG-TS by `saelower --from-svg`, into site/corpus_<name>.ts,
# each centred in a 400 x 400 canvas as the parity harness's reference PNGs
# are (aether-ui/vg/test/screenshots/svg-compare-aevg/<name>_ref.png).
# tests/spec_aevg_parity.ae renders each through the driver and measures the
# per-pixel error against that reference. Re-run after changing the emitter;
# the pages are committed so the spec needs no corpus checkout.
set -e
ROOT=$(cd "$(dirname "$0")/.." && pwd)
CORPUS="${SAE_SVG_CORPUS:-$ROOT/../not-ours/tsyne/cosyne/test/svg}"
for name in atom compass beacon heart AJ_Digital_Camera; do
    out="$ROOT/site/corpus_$name.ts"
    {
        echo "// site/corpus_$name.ts -- generated by tools/gen-corpus.sh; do not edit."
        echo "// The source SVG is the W3C/CVG corpus file $name.svg (cosyne/test/svg)."
        echo "ui.text(\"corpus: $name\");"
        echo "ui.hstack(0, () => {"
        echo "ui.spacer();"
        "$ROOT/target/saelower" --from-svg "$CORPUS/$name.svg" --size 400 | grep -v '^//' 
        echo "ui.spacer();"
        echo "});"
        echo "ui.btn(\"Home\", () => browserContext.changePage(\"/\"));"
    } > "$out"
    echo "wrote $out ($(wc -c < "$out") bytes)"
done
